PACKET_HEADER  = 0x7E

TYPE_NONE      = 0x01  #1: None
TYPE_GLOBAL    = 0x02  #  2: usually a type, function or class object, but just the name,
               	       #     so it has to exist for this to decode properly.
TYPE_INT64     = 0x03  #  3: 8 byte signed int
TYPE_INT32     = 0x04  #  4: 4 byte signed int
TYPE_INT16     = 0x05  #  5: 2 byte signed int
TYPE_INT8      = 0x06  #  6: 1 byte signed int
TYPE_MINUSONE  = 0x07  #  7: the value of -1
TYPE_ZERO      = 0x08  #  8: the value of 0
TYPE_ONE       = 0x09  #  9: the value of 1
TYPE_FLOAT     = 0x0a  # 10: 8 byte float
TYPE_FLOAT0    = 0x0b  # 11: the value of 0.0
TYPE_COMPLEX   = 0x0c  # 12: (not used, complex number)
TYPE_STRINGL   = 0x0d  # 13: string, longer than 255 characters using normal count*
TYPE_STRING0   = 0x0e  # 14: string, empty
TYPE_STRING1   = 0x0f  # 15: string, 1 character
TYPE_STRING    = 0x10  # 16: string, next byte is  0x00 -  0xff being the count.
TYPE_STRINGR   = 0x11  # 17: string, reference to line in strings.txt (stringTable)
TYPE_UNICODE   = 0x12  # 18: unicode string, next byte is count*
TYPE_BUFFER    = 0x13  # 19: buffer object... hmmm
TYPE_TUPLE     = 0x14  # 20: tuple, next byte is count*
TYPE_LIST      = 0x15  # 21: list, next byte is count*
TYPE_DICT      = 0x16  # 22: dict, next byte is count*
TYPE_INSTANCE  = 0x17  # 23: class instance, name of the class follows (as string, probably)
TYPE_BLUE      = 0x18  # 24: blue object.
TYPE_CALLBACK  = 0x19  # 25: callback
TYPE_PICKLE    = 0x1a  # 26: (not used, old pickle method)
TYPE_REF       = 0x1b  # 27: shared object reference
TYPE_CHECKSUM  = 0x1c  # 28: checksum of rest of stream
TYPE_COMPRESS  = 0x1d  # 29: (not used)
TYPE_UNUSED    = 0x1e  # 30: (not used)
TYPE_TRUE      = 0x1f  # 31: True
TYPE_FALSE     = 0x20  # 32: False
TYPE_PICKLER   = 0x21  # 33: standard pickle of undetermined size
TYPE_REDUCE    = 0x22  # 34: reduce protocol
TYPE_NEWOBJ    = 0x23  # 35: new style class object
TYPE_TUPLE0    = 0x24  # 36: tuple, empty
TYPE_TUPLE1    = 0x25  # 37: tuple, single element
TYPE_LIST0     = 0x26  # 38: list, empty
TYPE_LIST1     = 0x27  # 39: list, single element
TYPE_UNICODE0  = 0x28  # 40: unicode string, empty
TYPE_UNICODE1  = 0x29  # 41: unicode string, 1 character
TYPE_DBROW     = 0x2a  # 42: database row (quite hard, custom data format)
TYPE_STREAM    = 0x2b  # 43: embedded marshal stream
TYPE_TUPLE2    = 0x2c  # 44: tuple, 2 elements
TYPE_MARK      = 0x2d  # 45: marker (for the NEWOBJ/REDUCE iterators that follow them)
TYPE_UTF8      = 0x2e  # 46: UTF8 unicode string, buffer size count follows*
TYPE_LONG      = 0x2f  # 47: big int, byte count follows.
SHARED_FLAG    = 0x40